#!/bin/sh
set -e

cd /Users/noah/repos/hastur-server/infrastructure/mongrel2
# WARNING: on some systems the nohup doesn't work, like OSX
# so we're doing without
./worker.rb > profiles/worker.log &
echo  > ./profiles/chat/chat.pid
